/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tourtravel;

import java.awt.Image;
import javax.swing.ImageIcon;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author asus
 */
public class TravelGUI extends javax.swing.JFrame {

    /**
     * Creates new form TravelGUI
     */
    public TravelGUI() {
        initComponents();
        ImageIcon bg = new ImageIcon("Assets/Bg.png");
        ImageIcon scaledBg = new ImageIcon(bg.getImage().getScaledInstance(bg1.getWidth(), bg1.getHeight(), Image.SCALE_FAST));
        bg1.setIcon(scaledBg);
        bg2.setIcon(scaledBg);
        bg3.setIcon(scaledBg);
        PromptSupport.setPrompt("Username", UsernameLogin);
        PromptSupport.setPrompt("Password", PasswordLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButton = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        DaftarBtn = new javax.swing.JButton();
        bg1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PasswordLogin = new javax.swing.JTextField();
        UsernameLogin = new javax.swing.JTextField();
        kembali1Button = new javax.swing.JButton();
        bg2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        daftarNama = new javax.swing.JTextField();
        daftarEmail = new javax.swing.JTextField();
        daftarNomor = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        daftarPassword = new javax.swing.JPasswordField();
        daftarButton = new javax.swing.JButton();
        kembali2Button = new javax.swing.JButton();
        bg3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn);
        LoginBtn.setBounds(280, 200, 120, 40);

        DaftarBtn.setText("Daftar");
        DaftarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DaftarBtn);
        DaftarBtn.setBounds(280, 260, 120, 40);
        jPanel1.add(bg1);
        bg1.setBounds(0, 0, 720, 390);

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setLayout(null);

        PasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordLoginActionPerformed(evt);
            }
        });
        jPanel2.add(PasswordLogin);
        PasswordLogin.setBounds(260, 270, 170, 30);

        UsernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameLoginActionPerformed(evt);
            }
        });
        jPanel2.add(UsernameLogin);
        UsernameLogin.setBounds(260, 210, 170, 30);

        kembali1Button.setText("Kembali");
        kembali1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali1ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(kembali1Button);
        kembali1Button.setBounds(20, 350, 80, 23);
        jPanel2.add(bg2);
        bg2.setBounds(0, 0, 720, 390);

        jTabbedPane1.addTab("tab2", jPanel2);

        jPanel3.setLayout(null);

        daftarNama.setText("Nama");
        daftarNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarNamaActionPerformed(evt);
            }
        });
        jPanel3.add(daftarNama);
        daftarNama.setBounds(280, 110, 130, 30);

        daftarEmail.setText("Email");
        daftarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarEmailActionPerformed(evt);
            }
        });
        jPanel3.add(daftarEmail);
        daftarEmail.setBounds(280, 150, 130, 30);

        daftarNomor.setText("Nomor Telepon");
        daftarNomor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarNomorActionPerformed(evt);
            }
        });
        jPanel3.add(daftarNomor);
        daftarNomor.setBounds(280, 190, 130, 30);

        genderButton.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel3.add(jRadioButton1);
        jRadioButton1.setBounds(280, 280, 49, 21);

        genderButton.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jRadioButton2);
        jRadioButton2.setBounds(350, 280, 61, 21);

        daftarPassword.setText("jPasswordField1");
        daftarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(daftarPassword);
        daftarPassword.setBounds(280, 230, 130, 30);

        daftarButton.setText("Daftar");
        jPanel3.add(daftarButton);
        daftarButton.setBounds(310, 320, 70, 20);

        kembali2Button.setText("Kembali");
        kembali2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali2ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(kembali2Button);
        kembali2Button.setBounds(20, 350, 80, 23);
        jPanel3.add(bg3);
        bg3.setBounds(0, 0, 720, 390);

        jTabbedPane1.addTab("tab3", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 425));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void PasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordLoginActionPerformed

    private void UsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameLoginActionPerformed

    private void DaftarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarBtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_DaftarBtnActionPerformed

    private void daftarNomorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarNomorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarNomorActionPerformed

    private void daftarNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarNamaActionPerformed

    private void daftarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarEmailActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void daftarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarPasswordActionPerformed

    private void kembali2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali2ButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_kembali2ButtonActionPerformed

    private void kembali1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali1ButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_kembali1ButtonActionPerformed

    /**
     * @param args the command line arguments
     */             
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarBtn;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField PasswordLogin;
    private javax.swing.JTextField UsernameLogin;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JButton daftarButton;
    private javax.swing.JTextField daftarEmail;
    private javax.swing.JTextField daftarNama;
    private javax.swing.JTextField daftarNomor;
    private javax.swing.JPasswordField daftarPassword;
    private javax.swing.ButtonGroup genderButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kembali1Button;
    private javax.swing.JButton kembali2Button;
    // End of variables declaration//GEN-END:variables
}